// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'dart_assignment1_test.dart' as dart_assignment1_test;

void main() {
  dart_assignment1_test.main();
}
